import { CommonModule } from '@angular/common';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  OnInit,
  ViewChild,
} from '@angular/core';
import { InitWcService } from 'src/app/services/init-wc.service';

@Component({
  selector: 'app-mfs-wallet',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './mfs-wallet.component.html',
  styleUrls: ['./mfs-wallet.component.css'],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class MfsWalletComponent implements OnInit {
  @ViewChild('mfsWallet') mfsWallet: any;

  wcData = {};

  constructor(private initWcService: InitWcService) {}

  async ngOnInit() {
    // this.setToken(
    //   'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9ITm5KSHRnQ2JDTUlJRUtHZDRtNCJ9.eyJnTmFtZSI6IkhhcnNoIiwiZk5hbWUiOiJQYXRlbCIsImVtYWlsViI6InRydWUiLCJwaG9uZVYiOiJmYWxzZSIsImFsbEFjYyI6ImZhbHNlIiwic2VjTG9naW4iOiJ0cnVlIiwiYUwiOiJbe1wiY3RyeVwiOlwiZ3RcIixcImNhSWRcIjpcIjU1NzUyXCIsXCJzc0lkXCI6XCJ0YmRcIixcInBydFR5cGVcIjpcImluZGl2aWR1YWxcIixcImJhTFwiOlt7XCJiYUlkXCI6XCI4MjExNDY0MlwiLFwicHNJZFwiOlwiNTAyNDA0NDIwNTdcIixcImJ1XCI6XCJtb2JpbGVcIixcImJ0XCI6XCJwcmVwYWlkXCIsXCJwclwiOlwiZ3Vlc3RcIixcInNMXCI6W3tcImFJZFwiOlwiNTAyNDA0NDIwNTdcIixcIm1zaXNkbkxcIjpbe1wibXNpc2RuXCI6XCI1MDI0MDQ0MjA1N1wifV19XX0se1wiYmFJZFwiOlwiNzY1Njg4NjJcIixcInBzSWRcIjpcIjUwMjMwNjY4NjcxXCIsXCJidVwiOlwibW9iaWxlXCIsXCJidFwiOlwicHJlcGFpZFwiLFwicHJcIjpcImd1ZXN0XCIsXCJzTFwiOlt7XCJhSWRcIjpcIjUwMjMwNjY4NjcxXCIsXCJtc2lzZG5MXCI6W3tcIm1zaXNkblwiOlwiNTAyMzA2Njg2NzFcIn1dfV19XSxcInBPSWRcIjp7XCJkdFwiOlwiZHBpXCIsXCJkblwiOlwiTXpBd01qSXhNakl6TURFd01RPT1cIn19LHtcImN0cnlcIjpcImd0XCIsXCJjYUlkXCI6XCIxOTYxNDRcIixcInNzSWRcIjpcInRiZFwiLFwicHJ0VHlwZVwiOlwiYnVzaW5lc3NcIixcImJhTFwiOlt7XCJiYUlkXCI6XCIzMDQ3NDQyNlwiLFwicHNJZFwiOlwiNTAyMzIyNzA1NDBcIixcImJ1XCI6XCJtb2JpbGVcIixcImJ0XCI6XCJwb3N0cGFpZFwiLFwicHJcIjpcImd1ZXN0XCIsXCJzTFwiOlt7XCJhSWRcIjpcIjQwNTgzM1wiLFwicElkXCI6XCJTXCIsXCJtc2lzZG5MXCI6W3tcIm1zaXNkblwiOlwiNTAyMzIyNzA1NDBcIn1dfV19LHtcImJhSWRcIjpcIjMyNDE2MTAyXCIsXCJwc0lkXCI6XCI1MDIzMzEyMDc4MVwiLFwiYnVcIjpcIm1vYmlsZVwiLFwiYnRcIjpcInBvc3RwYWlkXCIsXCJwclwiOlwiZ3Vlc3RcIixcInNMXCI6W3tcImFJZFwiOlwiMTk3MjA5NFwiLFwicElkXCI6XCJTXCIsXCJtc2lzZG5MXCI6W3tcIm1zaXNkblwiOlwiNTAyMzMxMjA3ODFcIn1dfV19XSxcInBPSWRcIjp7XCJkdFwiOlwiZHBpXCIsXCJkblwiOlwiTWpFM01UQTVNakUzTURFd01RPT1cIn19LHtcImN0cnlcIjpcImd0XCIsXCJjYUlkXCI6XCI5ODY2MDFcIixcInNzSWRcIjpcInRiZFwiLFwicHJ0VHlwZVwiOlwiaW5kaXZpZHVhbFwiLFwiYmFMXCI6W3tcImJhSWRcIjpcIjgwMzYwNTA3XCIsXCJwc0lkXCI6XCI1MDI1MzIwMDk5N1wiLFwiYnVcIjpcIm1vYmlsZVwiLFwiYnRcIjpcInByZXBhaWRcIixcInByXCI6XCJndWVzdFwiLFwic0xcIjpbe1wiYUlkXCI6XCI1MDI1MzIwMDk5N1wiLFwibXNpc2RuTFwiOlt7XCJtc2lzZG5cIjpcIjUwMjUzMjAwOTk3XCJ9XX1dfV0sXCJwT0lkXCI6e1wiZHRcIjpcImRwaVwiLFwiZG5cIjpcIk1qWTRNakUwTnpBd01USXhPUT09XCJ9fV0iLCJoYXNQd2QiOiJ0cnVlIiwiaHliTG9naW4iOiJmYWxzZSIsInVuVHlwZSI6ImVtYWlsIiwidWNjIjoib25lYXBwIiwidWNjdCI6ImVtYWlsIiwiY3VzdG9tOlVVSUQiOiJjZWJkYmM1MC0xMDE2LTExZWUtOTkwMS05MzE2MWFlMzdmZWYiLCJjdHJ5IjoiZ3QiLCJjdCI6InVzZXJuYW1lLXBhc3N3b3JkLWF1dGhlbnRpY2F0aW9uIiwiZ2l2ZW5fbmFtZSI6IkhhcnNoIiwiZmFtaWx5X25hbWUiOiJQYXRlbCIsIm5pY2tuYW1lIjoiamJ1enppKzMiLCJuYW1lIjoiSGFyc2ggUGF0ZWwiLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvN2UwYmI0MWQ5ODgwMjk3MWY4OTMzNDU4ZDhhNDIzMmI_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZocC5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyNC0xMC0wM1QxNToxNjozNy4zNTRaIiwiZW1haWwiOiJqYnV6emkrM0Btb2JpcXVpdHlpbmMuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vaWQtdGlnby1ndC1zdGcudGlnb2Nsb3VkLm5ldC8iLCJhdWQiOiJoWExuRjZocVhvNEQ0U0hGZUlDc201eXpBaURhVzFpViIsImlhdCI6MTcyODQxNjc1NCwiZXhwIjoxNzI4NDIwMzU0LCJzdWIiOiJhdXRoMHxjZWJkYmM1MC0xMDE2LTExZWUtOTkwMS05MzE2MWFlMzdmZWYiLCJzaWQiOiItR3pFZWVYSUEySGVaNHJoenZSUnJuaXVjUjRpWDNqRSJ9.K7l7RkVo42NLdxQvYN3R6NcttQTUz40KuqZvvlzGHTGmIGQs7lyruYa0rSKtxF0WA02UruITdcLgUE9X6Tt6EP9Rj-0X1W2gaZHGQ5zC-O5ruPelIqgVLzniydXNIgi41-iVzm6LvsicL_rczh-jtmdrfwm1I4H3SwXaFJWLbxFXf9ZPD0xshr4a6cBVLl_AyL90vJrM-AHcvSzXOZCl6lDtSTn8juSyCgszx5ME9Yz5GBcllJzhngc8VMMsrfIdw_jAImvJZIOc3TjF82_WEI4VRYLmJbKKmKUM0a6a5GQaUVb_Q_lcV-IdRuTZP5pZazI2-jCYMGVta7DygpXemg'
    // );

    this.wcData = {
      billingType: 'prepaid',
      bussinesUnit: 'mobile',
      channel: 'oneappweb',
      countryCode: 'GT',
      deviceId: this.initWcService?.wcData?.deviceId,
      id: this.initWcService?.wcData?.id,
      idTyoe: 'subscribers',
      plataform: this.initWcService?.wcData?.plataform,
      urlBase: 'https://micuenta2-tigo-com-gt-stg.tigocloud.net',
    };
    window.document.addEventListener('wcRefreshToken', (e: any) => {
      console.log('wcRefreshToken', e);

      // this.setToken(
      //   'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9ITm5KSHRnQ2JDTUlJRUtHZDRtNCJ9.eyJnTmFtZSI6IkhhcnNoIiwiZk5hbWUiOiJQYXRlbCIsImVtYWlsViI6InRydWUiLCJwaG9uZVYiOiJmYWxzZSIsImFsbEFjYyI6ImZhbHNlIiwic2VjTG9naW4iOiJ0cnVlIiwiYUwiOiJbe1wiY3RyeVwiOlwiZ3RcIixcImNhSWRcIjpcIjU1NzUyXCIsXCJzc0lkXCI6XCJ0YmRcIixcInBydFR5cGVcIjpcImluZGl2aWR1YWxcIixcImJhTFwiOlt7XCJiYUlkXCI6XCI4MjExNDY0MlwiLFwicHNJZFwiOlwiNTAyNDA0NDIwNTdcIixcImJ1XCI6XCJtb2JpbGVcIixcImJ0XCI6XCJwcmVwYWlkXCIsXCJwclwiOlwiZ3Vlc3RcIixcInNMXCI6W3tcImFJZFwiOlwiNTAyNDA0NDIwNTdcIixcIm1zaXNkbkxcIjpbe1wibXNpc2RuXCI6XCI1MDI0MDQ0MjA1N1wifV19XX0se1wiYmFJZFwiOlwiNzY1Njg4NjJcIixcInBzSWRcIjpcIjUwMjMwNjY4NjcxXCIsXCJidVwiOlwibW9iaWxlXCIsXCJidFwiOlwicHJlcGFpZFwiLFwicHJcIjpcImd1ZXN0XCIsXCJzTFwiOlt7XCJhSWRcIjpcIjUwMjMwNjY4NjcxXCIsXCJtc2lzZG5MXCI6W3tcIm1zaXNkblwiOlwiNTAyMzA2Njg2NzFcIn1dfV19XSxcInBPSWRcIjp7XCJkdFwiOlwiZHBpXCIsXCJkblwiOlwiTXpBd01qSXhNakl6TURFd01RPT1cIn19LHtcImN0cnlcIjpcImd0XCIsXCJjYUlkXCI6XCIxOTYxNDRcIixcInNzSWRcIjpcInRiZFwiLFwicHJ0VHlwZVwiOlwiYnVzaW5lc3NcIixcImJhTFwiOlt7XCJiYUlkXCI6XCIzMDQ3NDQyNlwiLFwicHNJZFwiOlwiNTAyMzIyNzA1NDBcIixcImJ1XCI6XCJtb2JpbGVcIixcImJ0XCI6XCJwb3N0cGFpZFwiLFwicHJcIjpcImd1ZXN0XCIsXCJzTFwiOlt7XCJhSWRcIjpcIjQwNTgzM1wiLFwicElkXCI6XCJTXCIsXCJtc2lzZG5MXCI6W3tcIm1zaXNkblwiOlwiNTAyMzIyNzA1NDBcIn1dfV19LHtcImJhSWRcIjpcIjMyNDE2MTAyXCIsXCJwc0lkXCI6XCI1MDIzMzEyMDc4MVwiLFwiYnVcIjpcIm1vYmlsZVwiLFwiYnRcIjpcInBvc3RwYWlkXCIsXCJwclwiOlwiZ3Vlc3RcIixcInNMXCI6W3tcImFJZFwiOlwiMTk3MjA5NFwiLFwicElkXCI6XCJTXCIsXCJtc2lzZG5MXCI6W3tcIm1zaXNkblwiOlwiNTAyMzMxMjA3ODFcIn1dfV19XSxcInBPSWRcIjp7XCJkdFwiOlwiZHBpXCIsXCJkblwiOlwiTWpFM01UQTVNakUzTURFd01RPT1cIn19LHtcImN0cnlcIjpcImd0XCIsXCJjYUlkXCI6XCI5ODY2MDFcIixcInNzSWRcIjpcInRiZFwiLFwicHJ0VHlwZVwiOlwiaW5kaXZpZHVhbFwiLFwiYmFMXCI6W3tcImJhSWRcIjpcIjgwMzYwNTA3XCIsXCJwc0lkXCI6XCI1MDI1MzIwMDk5N1wiLFwiYnVcIjpcIm1vYmlsZVwiLFwiYnRcIjpcInByZXBhaWRcIixcInByXCI6XCJndWVzdFwiLFwic0xcIjpbe1wiYUlkXCI6XCI1MDI1MzIwMDk5N1wiLFwibXNpc2RuTFwiOlt7XCJtc2lzZG5cIjpcIjUwMjUzMjAwOTk3XCJ9XX1dfV0sXCJwT0lkXCI6e1wiZHRcIjpcImRwaVwiLFwiZG5cIjpcIk1qWTRNakUwTnpBd01USXhPUT09XCJ9fV0iLCJoYXNQd2QiOiJ0cnVlIiwiaHliTG9naW4iOiJmYWxzZSIsInVuVHlwZSI6ImVtYWlsIiwidWNjIjoib25lYXBwIiwidWNjdCI6ImVtYWlsIiwiY3VzdG9tOlVVSUQiOiJjZWJkYmM1MC0xMDE2LTExZWUtOTkwMS05MzE2MWFlMzdmZWYiLCJjdHJ5IjoiZ3QiLCJjdCI6InVzZXJuYW1lLXBhc3N3b3JkLWF1dGhlbnRpY2F0aW9uIiwiZ2l2ZW5fbmFtZSI6IkhhcnNoIiwiZmFtaWx5X25hbWUiOiJQYXRlbCIsIm5pY2tuYW1lIjoiamJ1enppKzMiLCJuYW1lIjoiSGFyc2ggUGF0ZWwiLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvN2UwYmI0MWQ5ODgwMjk3MWY4OTMzNDU4ZDhhNDIzMmI_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZocC5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyNC0xMC0yM1QxNzo1MzowMi4yODBaIiwiZW1haWwiOiJqYnV6emkrM0Btb2JpcXVpdHlpbmMuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vaWQtdGlnby1ndC1zdGcudGlnb2Nsb3VkLm5ldC8iLCJhdWQiOiJoWExuRjZocVhvNEQ0U0hGZUlDc201eXpBaURhVzFpViIsImlhdCI6MTcyOTg2MDU5MiwiZXhwIjoxNzI5ODY0MTkyLCJzdWIiOiJhdXRoMHxjZWJkYmM1MC0xMDE2LTExZWUtOTkwMS05MzE2MWFlMzdmZWYiLCJzaWQiOiJRYUJkcEZQZ2p1ZHJ0VzBtSTBKSzNPdjZfWlJwRnRsbiJ9.mXBkgoZWIX813VHgw-slS2c_78hTfK7fST0eTZDhCnHcnDvsGJlXDpBaiqqwhX-baO9CSiEPpoBqttGypnoDqpzAez6ZBSTAtqQ4ZgoniPgWrpR3OgfFLbBD8tHRpzm3QdiwNh0rTL2UPcPOz5uAb_fNeN-VQJ6XXkuj_CnOUEH6kVgOt7q_PJfaCwHQYWGwH7fGV_p04RbvcFXa0f0foo9GRq-WhqtyYizLtXpUBZiuLN7GupC9thPaNapNjSk_nktK7mGDW2Mmz2gxppaGolv3R9omwaFhjvNOXhWEqtbZ5h-SjC5ixW5UzOlFJan_BaTvWyHqfTPhXwmrPIfBPg'
      // );
    });
  }

  setToken(token: string) {
    localStorage.setItem('IdToken', token);
  }
}
